[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
yew={version="0.21",features=["car"]}
yew-hooks="0.3"
web-sys={version="0.3",features=["HtmlTextAreaElement"]}

common={path="../common"}
serde={workspace=true}
chrono={workspace=true}